version: "3.8"
services:
  orchestrator:
    build: .
    environment:
      - AUDIT_SECRET=${AUDIT_SECRET}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: ["python", "FedGNN_advanced/orchestrator.py"]
