replicaCount: 1
image:
  repository: your-registry/fl-server
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"
persistence:
  enabled: true
  existingClaimModel: model-pvc
  existingClaimDataset: dataset-pvc
service:
  type: LoadBalancer
  portGrpc: 50051
  portMetrics: 8000
