# File: k8s/secret-example.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fedgnn-kms-secret
  namespace: fedgnn
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: fedgnn-kms
    creationPolicy: Owner
  data:
    - secretKey: FEDGNN_KMS_PROVIDER
      remoteRef:
        key: /fedgnn/config/kms_provider
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /fedgnn/creds/aws access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /fedgnn/creds/aws secret_access_key
