apiVersion: v1
kind: Service
metadata:
  name: fl-server
spec:
  selector:
    app: fl-server
  type: LoadBalancer
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
